spring.application.name=LibSmart
spring.devtools.restart.enabled=false

# Database
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.aavlfkezkiofojgpkswt
spring.datasource.password=VSvvwo7af73nhQ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.max-lifetime=240000
spring.datasource.hikari.keepalive-time=120000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
server.tomcat.max-swallow-size=-1

server.port=8081

# JWT
app.jwt.secret=libsmart-super-secret-key-2024-make-this-long-enough-for-security
app.jwt.expiration-ms=86400000